version: "3"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - app-tier
    depends_on:
      - zookeeper

  first-service:
    container_name: "first-service"
    build:
      context: ./first-service
      dockerfile: Dockerfile
    networks:
      - app-tier
    depends_on:
      - kafka

  second-service:
    container_name: "second-service"
    build:
      context: ./second-service
      dockerfile: Dockerfile
    networks:
      - app-tier
    depends_on:
      - kafka