spring.kafka:
  bootstrap-servers: localhost:9092
  producer:
    topic: ping.events
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  consumer:
    topic: pong.events
    group-id: first-service-consumer
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  properties.spring.json.trusted.packages: "*"
